// Generated by https://quicktype.io

export interface Sale {
  id: string;
  status: string;
  sellerId: string;
  seller: string;
  date: string;
  subtotal: string;
  taxes: string;
  total: string;
  items: Item[];
}

export interface Item {
  name: string;
  price: number;
  quantity: number;
}
