// Generated by https://quicktype.io

export interface Employee {
  id: string;
  employeeType: string;
  firstName: string;
  secondName?: string;
  lastName: string;
  secondSurName?: string;
  idNumber: string;
  phoneNumber: string;
  email: string;
  password: string;
  profilePictureUrl: string;
  address: string;
}

export interface validatedCredentialsProps {
  email: string
  password: string
}